### ISSUE TITLE
Issue building the app

### ISSUE THREAD

**Issue by DrZoidberg09** [rcdevs/nextcloud_openotp_sign#1]
Hi there,

I am trying to build the app. I have the depencies present.

And when I am running "make", the following is showing:

>  [Composer\Json\JsonValidationException]                                                                     
  "./composer.json" does not match the expected JSON schema:                                                  
>    - name : Does not match the regex pattern ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$ 

Any ideas why that is happening?

Thank you so much!

**Comment by rcdevs** [comment]
Hi,

The README.md is the default one generated by the Nextcloud and does not reflect the instructions needed to build the app. We should definitely update this README.md for people that would like to build from source

For now, here are the instructions to build a development release :

`
npm install
npm run dev
`

Or you can use `npm run build` for a production release

**Comment by rcdevs** [comment]
Hi,

Finally, we fixed the Makefile instead to edit the README.md

Best regards,
