### ISSUE TITLE
File stored in /tmp

### ISSUE THREAD

**Issue by acsfer** [rcdevs/nextcloud_openotp_sign#2]
Hi,

is there a reason why a file like `wsdl-user-003226803cd316350a4b1f542595adb77e` is stored in `/tmp` even if php is configured with
```
php_admin_value[doc_root]       = /home/$pool/app
php_admin_value[upload_tmp_dir] = /home/$pool/tmp
php_admin_value[sys_temp_dir]   = /home/$pool/tmp
```
Thanks.

**Comment by rcdevs** [comment]
Hi,

Maybe it is related to how PHP deals with the tmp folder for its own SoapClient cache.

Anyway, we just releases a version 1.2.1 which do not use anymore PHP SoapClient but NuSOAP so our app will be compatible on the stock official docker container of NextCloud so you will not have a cache of WSDL anymore and we do not explicitly use the tmp folder in other parts of our application so I am closing the ticket.

Best regards,

**Comment by acsfer** [comment]
Thanks. Please also check https://github.com/rcdevs/nextcloud_openotp_sign/commit/4ae156cdc2e6602df9261235576141ef830735b0#commitcomment-67648276
