### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'substring')

### ISSUE THREAD

**Issue by solracsf** [rcdevs/nextcloud_openotp_sign#4]
Happy to provide more info if needed.

![image](https://user-images.githubusercontent.com/12234510/201165972-958b7d69-74fe-4a05-9e67-18e022b236cb.png)

**Comment by rcdevs** [comment]
Hello solracsf
Should be fixed now.
Supports NxC27 too.
Sorry for huge delay...
Regards
EJB
